from .db_init import init_db
from .user import (
    User,
    create_user,
    verify_user,
    get_user_password_changed_at,
    update_user_password,
    update_user_username,
    get_login_attempts,
    record_login_attempt,
    clear_login_attempts,
    delete_user,
)

from .tasks import (
    get_categories,
    get_dashboard_categories,
    add_category,
    delete_category,
    update_category,
    get_last_processed_date,
    set_last_processed_date,
    get_everyday_tasks,
    get_dashboard_day_data,
    add_everyday_task,
    toggle_everyday_task,
    delete_everyday_task,
    reorder_tasks,
    ensure_today_tasks,
    get_today_tasks,
    add_task,
    get_task,
    update_task,
    complete_task,
    delete_task,
    void_task,
    reconcile_days,
    copy_yesterday_tasks,
    calculate_efficiency,
    get_history_data,
    get_efficiency_timeseries,
    delete_all_user_tasks,
)

from .gamification import (
    get_gamification_stats,
    update_streak_on_completion,
    check_and_update_perfect_day,
    update_type_complete_count,
    check_and_award_freeze,
    get_user_badges,
    check_and_award_badges,
    reset_gamification_stats,
    delete_user_gamification,
)

from .monsters import (
    get_monster_types,
    get_user_monsters,
    get_recent_monsters,
    award_monster,
    has_migrated_monsters,
    export_collection,
    import_collection,
    seed_monsters_and_badges,
)

__all__ = [
    "init_db",
    # User
    "User",
    "create_user",
    "verify_user",
    "get_user_password_changed_at",
    "update_user_password",
    "update_user_username",
    "get_login_attempts",
    "record_login_attempt",
    "clear_login_attempts",
    "delete_user",
    # Tasks
    "get_categories",
    "get_dashboard_categories",
    "add_category",
    "delete_category",
    "update_category",
    "get_last_processed_date",
    "set_last_processed_date",
    "get_everyday_tasks",
    "get_dashboard_day_data",
    "add_everyday_task",
    "toggle_everyday_task",
    "delete_everyday_task",
    "reorder_tasks",
    "ensure_today_tasks",
    "get_today_tasks",
    "add_task",
    "get_task",
    "update_task",
    "complete_task",
    "delete_task",
    "void_task",
    "reconcile_days",
    "copy_yesterday_tasks",
    "calculate_efficiency",
    "get_history_data",
    "get_efficiency_timeseries",
    "delete_all_user_tasks",
    # Gamification
    "get_gamification_stats",
    "update_streak_on_completion",
    "check_and_update_perfect_day",
    "update_type_complete_count",
    "check_and_award_freeze",
    "get_user_badges",
    "check_and_award_badges",
    "reset_gamification_stats",
    "delete_user_gamification",
    # Monsters
    "get_monster_types",
    "get_user_monsters",
    "get_recent_monsters",
    "award_monster",
    "has_migrated_monsters",
    "export_collection",
    "import_collection",
    "seed_monsters_and_badges",
]
